# Generated by Django 5.2.4 on 2025-07-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(default=0),
        ),
    ]
