[project]
name = "ecom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "pillow>=11.3.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
